name: em
description: A expense management application.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  
  # For Language Translations
  easy_localization: ^3.0.1

  # Deep Link Handling
  uni_links: ^0.5.1
  
  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10

  # Data Class Handling
  equatable: ^2.0.5

  # Directory Handling
  path_provider: ^2.0.11

  # For Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Device Info
  device_info_plus: ^8.0.0

  # BLOC Architecture
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0

  # Social Login
  google_sign_in: ^5.4.3

  # Dependency Injection
  get_it: ^7.2.0

  # Extra Icons
  font_awesome_flutter: ^10.3.0
  
  # Widgets
  dropdown_button2: ^1.9.2

  # Calendar View
  syncfusion_flutter_calendar: ^20.3.57

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_extra_bold.ttf
          weight: 900
        - asset: assets/fonts/poppins_bold.ttf
          weight: 800
        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_regular.ttf
          weight: 300
        - asset: assets/fonts/poppins_light.ttf
          weight: 100
