name: em
description: A expense management application.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # For Language Translations
  easy_localization: ^3.0.1

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10

  # For Local Storage
  hive: ^2.2.3

  # Device Info
  device_info_plus: ^8.0.0

  # BLOC Architecture
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0

  # Social Login
  google_sign_in: ^5.4.3

  # Dependency Injection
  get_it: ^7.2.0

flutter:

  uses-material-design: true

